#!/bin/bash 

# amd64
docker buildx build --platform linux/amd64 -t agtix:amd64 --load .
docker save agtix:amd64 > agtix-amd64.tar

# arm64
docker buildx build --platform linux/arm64 -t agtix:arm64 --load .
docker save agtix:arm64 > agtix-arm64.tar
